version: '3'
services:
  backend:
    build: ./scalable-video-hosting-backend
    depends_on:
      - db
      - redis
    restart: always 
    env_file:
      - s3.env
      - db.env
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db

  db:
    image: postgres:16
    env_file:
      - db.env
    ports:
      - "5432:5432" # For testing
    volumes:
      - "data-volume:/var/lib/postgresql/data"

  frontend:
    build:
      context: ./scalable-video-hosting-frontend
      dockerfile: compose.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  redis:
    image: redis:7
    volumes:
      - "data-volume:/data"

  convert-worker:
    image: scalable-video-hosting-worker
    build: ./scalable-video-hosting-worker
    depends_on:
      - redis
      - backend
    env_file:
      - s3.env
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: convert

  thumbnail-worker:
    image: scalable-video-hosting-worker
    build: ./scalable-video-hosting-worker
    depends_on:
      - redis
      - backend
    env_file:
      - s3.env
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: thumbnail

  chunk-worker:
    image: scalable-video-hosting-worker
    build: ./scalable-video-hosting-worker
    depends_on:
      - redis
      - backend
    env_file:
      - s3.env
    environment:
      REDIS_HOST: redis
      WORKER_TYPE: chunk

volumes:
  data-volume:
