apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: svh-thumbnail-worker
  name: svh-thumbnail-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svh-thumbnail-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svh-thumbnail-worker
    spec:
      containers:
      - image: ghcr.io/thanatadcs/scalable-video-hosting-worker:latest
        name: scalable-video-hosting-worker
        resources: {}
        env:
          - name: WORKER_TYPE
            value: "thumbnail"
        envFrom:
          - configMapRef:
              name: s3-config
          - secretRef:
              name: s3-secret
          - configMapRef:
              name: hostname-config
status: {}
